CSCoreBundle:
    resource: "@CSCoreBundle/Controller/"
    type:     annotation
    prefix:   /

CSInstallerBundle:
    resource: "@CSInstallerBundle/Controller/"
    type:     annotation
    prefix:   /

CSUserBundle:
    resource: "@CSUserBundle/Controller/"
    type:     annotation
    prefix:   /

CSClientBundle:
    resource: "@CSClientBundle/Controller/"
    type:     annotation
    prefix:   /

_bazinga_exposetranslation:
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
